"""
Chat History Persistence and Summarisation Compaction Service.

This module provides background tasks for saving dialogue turns to PostgreSQL
and automatically generating/updating running summaries of past conversations
to prevent context window overflow during multi-turn chats.
"""

from core.chat_history_store import ChatHistoryStore
from services.agent_completion import agent_complete


def save_and_compact_workflow(
    session_id: str,
    user_question: str,
    assistant_answer: str,
    old_summary: str,
    metadata: dict = None
) -> None:
    """Save the conversation turn and update the session running summary asynchronously.

    Designed to run as a FastAPI :class:`~fastapi.BackgroundTasks` job so that API latency
    is minimized. It:
    1. Persists the user question and assistant answer to ``chat_messages``.
    2. Checks conversation turn threshold (skips summary update if fewer than 10 messages).
    3. Prompts a lightweight LLM to integrate the latest turn into the running summary.
    4. Upserts the new summary string into ``chat_summaries``.

    Args:
        session_id: Unique string identifier for the chat session.
        user_question: The natural language question submitted by the user.
        assistant_answer: The final response string generated by the assistant.
        old_summary: The existing running summary text for the session prior to this turn.
        metadata: Optional dictionary of extra metadata associated with the turn.
    """
    # 1. Save raw messages
    ChatHistoryStore.save_message(session_id, "user", user_question, metadata)
    ChatHistoryStore.save_message(session_id, "assistant", assistant_answer)

    # 2. Skip summarization for short conversation
    history = ChatHistoryStore.get_last_20_message(session_id)

    if len(history) < 10:
        return

    # 3. Call LLM to update summary
    messages = [
        {
            "role": "system",
            "content": (
                "You are an assistant responsible for maintaining the running summary "
                "of a conversation between a user and a PDF chatbot. "
                "Integrate the new conversation turn into the existing summary. "
                "Keep the output extremely concise (under 3 sentences) focusing on "
                "core facts, user preferences, and key answers. Return plain text only"
            )
        },
        {
            "role": "user",
            "content": (
                f"Existing Summary:\n{old_summary}"
                f"New Turn:\n"
                f"User: {user_question}\n"
                f"Assistant: {assistant_answer}"
            )
        }
    ]
    completion = agent_complete(messages, is_grading=True)
    new_summary = completion.choices[0].message.content.strip()

    # 4. Save new summary back to Neon DB
    ChatHistoryStore.update_summary(session_id, new_summary)

